### ISSUE TITLE
Build errors using clang

### ISSUE THREAD

**Issue by napcode** [original-male/ntk#6]
NTK can't be build with clang (3.7.1) right now:
`
../src/Fl_x.cxx:2196:31: error: 'FORCE_POSITION' is a protected member of 'Fl_Widget'
  if (w->flags() & Fl_Widget::FORCE_POSITION) 
`

gcc has no issues compiling this code. Nevertheless, the enum is indeed protected and enums obey the same visibility rules as methods etc.. I guess clang is correct here and the code should be changed.

**Comment by napcode** [comment]
This can be closed.
